export const TAG_TYPES = {
  POST: "POST",
  NOTIFICATION: "NOTIFICATION",
  CONVERSATION_LIST: "CONVERSATION_LIST",
  PROFILE: "PROFILE",
  RECOMMENDATION_USER: "RECOMMENDATION_USER",
};

export enum HTTP_METHOD {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
  PATCH = "PATCH",
}

export const PARAM_FIELD = {
  PAGE_INDEX: "PageIndex",
  PAGE_SIZE: "PageSize",
};
